### ISSUE TITLE
Add vs_currency to /global

### ISSUE THREAD

**Issue by georgeherby** [yegor-pelykh/coingecko_api#2]
I know the documentation does not state that the /global endpoint supports `vs_currency`, but it does in fact support it.

Eg. 
With vs currency as gbp -> https://api.coingecko.com/api/v3/global?vs_currency=gbp
When the vs_currency is provided gbp is present in the response

Without -> https://api.coingecko.com/api/v3/global

**Comment by yegor-pelykh** [comment]
Hi @georgeherby 
Thank you for your interest in improving this package!

I tried to put various other currencies in this request
https://api.coingecko.com/api/v3/global?vs_currency=usd
https://api.coingecko.com/api/v3/global?vs_currency=gbp
https://api.coingecko.com/api/v3/global?vs_currency=uah
https://api.coingecko.com/api/v3/global?vs_currency=btc
etc

But for some reason, all the numbers indicated in the sections `total_market_cap`, `total_volume`, `market_cap_percentage` were the same for each of them. Do you still think that specifying the currency affects the response?

**Comment by georgeherby** [comment]
Oh I think this is my error apologies. I had cached an old list of vs_currencies and was passing using this to build the URLs (I am replacing my network calls with this library) which turns out it was doing nothing and working by coincidence.

I will close this issue
