### ISSUE TITLE
test ^1.20.1 issues

### ISSUE THREAD

**Issue by georgeherby** [yegor-pelykh/coingecko_api#4]
Just updated to 1.0.2 and I am now getting this error. I am guessing test 1.21.1 is not in the stable channel flutter sdk.

```
Because every version of flutter_test from sdk depends on test_api 0.4.3 and test >=1.20.0 depends on test_api 0.4.9, flutter_test from sdk is incompatible with test >=1.20.0.
And because coingecko_api >=1.0.2 depends on test ^1.20.1, flutter_test from sdk is incompatible with coingecko_api >=1.0.2.
```

Flutter version -> Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-x64, locale en-GB

**Comment by yegor-pelykh** [comment]
Yes, there was a problem with the test package, the project was referring to it incorrectly.
Now it is fixed. https://github.com/yegor-pelykh/coingecko_api/commit/7457780d4fd2abe0ff1913e3b56ad9146bfaefd4

Could you please update your package version. Is it working now?

**Comment by georgeherby** [comment]
Working fine now thanks :)
