### ISSUE TITLE
cant find image

### ISSUE THREAD

**Issue by maryfallah** [yegor-pelykh/coingecko_api#5]
how can i add image of the coin?

**Comment by yegor-pelykh** [comment]
Do you mean how to get the image of the coin?

You can use methods:
- `coins.getCoinData()` - **to get data on one specific coin**
- `coins.listCoinMarkets()` - **to get data on multiple coins at once**

Then, in the result data object, look at the `image` field.
It contains the url to the image.

**Comment by maryfallah** [comment]
I asked my question here :

https://stackoverflow.com/questions/72532115/calling-coin-gecko-for-image-of-bitcoin-in-flutter-app

I hope you can help me

**Comment by yegor-pelykh** [comment]
I understood your issue.
But since it is not a problem of this package, and also it has already been solved on the page you indicated, then I close this issue.

Thank you for using this package!

**Comment by maryfallah** [comment]
Thank you so much for this package that made flutter much more cool. Wish
you the best 👌
